---
- hosts: nodo1
  tasks:
    - name: Instalar Apache
      yum:
        name: httpd
        state: latest
    - name: Crear directorio fact
      file: 
        path: /etc/ansible/facts.d
        state: directory
        recurse: true
    - name: copiar archivo new facts
      copy:
        src: first.fact
        dest: /etc/ansible/facts.d
#    - name: Abrir puertos firewalld
#      firewalld:
#        service: http
#        permanent: true
#        immediate: true
#        state: enabled
    - name: Obtener Fact IP Address
      copy:
        content: " El nombre del servidor es {{ ansible_hostname }}, y la direccion IP es {{ ansible_default_ipv4.address }}"
        dest: /var/www/html/index.html
    - name: Habilitar servicio de apache
      service:
        name: httpd
        state: started
        enabled: true
...
