---
- hosts: nodo2
  tasks:
    - name: Instalando apache
      yum:
        name: httpd
        state: latest
    - name: Iniciar Servicios
      service:
        name: httpd
        state: started
        enabled: true
    - name: Crear contenido de index.html
      copy:
        content: "Bienvenido a mi servidor web"
        dest: /var/www/html/index.html
        mode: 0644
    - name: Modificando index.html
      lineinfile:
        path: /var/www/html/index.html
        insertbefore: '^Bienvenido'
        line: 'Esto es una prueba'
    - name: Modificando index.html
      lineinfile:
        path: /var/www/html/index.html
        regexp: '^Bienvenido'
        line: 'SELINUX=enforcing'
        
#    - name: Abrir puertos Firewall
#      firewalld:
#        service: httpd
#        immediate: true
#        permanent: true
#        state: enable
...
